version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: radar_db
    restart: always
    environment:
      POSTGRES_USER: dazaran
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: radar_core
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
