name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Обновили до v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4 # ВОТ ТУТ БЫЛА ОШИБКА, замени на v4
        with:
          name: glitch-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
